version: '3.8'

services:
  coordinator:
    build: 
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    command: python -m coordinator.core.coordinator
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ../../logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  worker:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    command: python -m coordinator.workers.worker
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKER_TYPE=general
      - TORCH_NUM_THREADS=4
      - TF_NUM_THREADS=4
    depends_on:
      - coordinator
      - redis
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 2G

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

volumes:
  redis_data:
  prometheus_data: