global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'coordinator'
    static_configs:
      - targets: ['coordinator:8000']
    metrics_path: '/metrics'

  - job_name: 'workers'
    static_configs:
      - targets: ['worker:8000']
    metrics_path: '/metrics'